In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
url_24 = "https://drive.google.com/uc?id=1VlMOY7PVIiDdxNWHMclGl9ZDaf7UdUE4"
url_25 = "https://drive.google.com/uc?id=1q3OBWP2bW07m-89bNpfO7Vtq0MhKKIeK"

df_24 = pd.read_csv(url_24)
df_25 = pd.read_csv(url_25)

In [ ]:
col_24 = df_24.columns
col_25 = df_25.columns

print(col_24)
print(col_25)
print(f"df_24 tiene {len(col_24)} columnas")
print(f"df_25 tiene: {len(col_25)} columnas")

Index(['player_id', 'version', 'name', 'full_name', 'description', 'image',
       'height_cm', 'weight_kg', 'dob', 'positions', 'overall_rating',
       'potential', 'value', 'wage', 'preferred_foot', 'weak_foot',
       'skill_moves', 'international_reputation', 'work_rate', 'body_type',
       'real_face', 'release_clause', 'specialities', 'club_id', 'club_name',
       'club_league_id', 'club_league_name', 'club_logo', 'club_rating',
       'club_position', 'club_kit_number', 'club_joined',
       'club_contract_valid_until', 'country_id', 'country_name',
       'country_league_id', 'country_league_name', 'country_flag',
       'country_rating', 'country_position', 'country_kit_number', 'crossing',
       'finishing', 'heading_accuracy', 'short_passing', 'volleys',
       'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control',
       'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance',
       'shot_power', 'jumping', 'stamina', 'strength', 'long_shots',
       'aggression', 'interceptions', 'positioning', 'vision', 'penalties',
       'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle',
       'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning',
       'gk_reflexes', 'play_styles'],
      dtype='object')
Index(['Unnamed: 0.1', 'Unnamed: 0', 'Rank', 'Name', 'OVR', 'PAC', 'SHO',
       'PAS', 'DRI', 'DEF', 'PHY', 'Acceleration', 'Sprint Speed',
       'Positioning', 'Finishing', 'Shot Power', 'Long Shots', 'Volleys',
       'Penalties', 'Vision', 'Crossing', 'Free Kick Accuracy',
       'Short Passing', 'Long Passing', 'Curve', 'Dribbling', 'Agility',
       'Balance', 'Reactions', 'Ball Control', 'Composure', 'Interceptions',
       'Heading Accuracy', 'Def Awareness', 'Standing Tackle',
       'Sliding Tackle', 'Jumping', 'Stamina', 'Strength', 'Aggression',
       'Position', 'Weak foot', 'Skill moves', 'Preferred foot', 'Height',
       'Weight', 'Alternative positions', 'Age', 'Nation', 'League', 'Team',
       'play style', 'url', 'GK Diving', 'GK Handling', 'GK Kicking',
       'GK Positioning', 'GK Reflexes'],
      dtype='object')
df_24 tiene 76 columnas
df_25 tiene: 58 columnas

In [ ]:
df_24 = df_24.drop(columns=['player_id', 'version', 'name', 'description', 'image',
       'dob', 'potential', 'value', 'wage', 'skill_moves', 'international_reputation', 'work_rate', 'body_type',
       'real_face', 'release_clause', 'specialities', 'club_id', 'club_name',
       'club_league_id', 'club_league_name', 'club_logo', 'club_rating',
       'club_position', 'club_kit_number', 'club_joined',
       'club_contract_valid_until', 'country_id', 'country_name',
       'country_league_id', 'country_league_name', 'country_flag',
       'country_rating', 'country_position', 'country_kit_number', 'play_styles'])
df_25 = df_25.drop(columns=['Unnamed: 0.1', 'Unnamed: 0', 'Rank', 'Nation', 'League',
                            'Team', 'play style', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY',
                            'url', 'Alternative positions', 'Age', 'Skill moves'])

In [ ]:
print(df_24.columns)
print(df_25.columns)

Index(['full_name', 'height_cm', 'weight_kg', 'positions', 'overall_rating',
       'preferred_foot', 'weak_foot', 'crossing', 'finishing',
       'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve',
       'fk_accuracy', 'long_passing', 'ball_control', 'acceleration',
       'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power',
       'jumping', 'stamina', 'strength', 'long_shots', 'aggression',
       'interceptions', 'positioning', 'vision', 'penalties', 'composure',
       'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving',
       'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes'],
      dtype='object')
Index(['Name', 'OVR', 'Acceleration', 'Sprint Speed', 'Positioning',
       'Finishing', 'Shot Power', 'Long Shots', 'Volleys', 'Penalties',
       'Vision', 'Crossing', 'Free Kick Accuracy', 'Short Passing',
       'Long Passing', 'Curve', 'Dribbling', 'Agility', 'Balance', 'Reactions',
       'Ball Control', 'Composure', 'Interceptions', 'Heading Accuracy',
       'Def Awareness', 'Standing Tackle', 'Sliding Tackle', 'Jumping',
       'Stamina', 'Strength', 'Aggression', 'Position', 'Weak foot',
       'Preferred foot', 'Height', 'Weight', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes'],
      dtype='object')

In [ ]:
column_mapping = {
    'full_name': 'Name',
    'height_cm': 'Height',
    'weight_kg': 'Weight',
    'overall_rating': 'OVR',
    'positions': 'Position',
    'preferred_foot': 'Preferred foot',
    'weak_foot': 'Weak foot',
    'crossing': 'Crossing',
    'finishing': 'Finishing',
    'heading_accuracy': 'Heading Accuracy',
    'acceleration': 'Acceleration',
    'short_passing': 'Short Passing',
    'long_passing': 'Long Passing',
    'sprint_speed': 'Sprint Speed',
    'gk_diving': 'GK Diving',
    'gk_handling': 'GK Handling',
    'gk_kicking': 'GK Kicking',
    'gk_positioning': 'GK Positioning',
    'gk_reflexes': 'GK Reflexes',
    'ball_control': 'Ball Control',
    'shot_power': 'Shot Power',
    'long_shots': 'Long Shots',
    'stamina': 'Stamina',
    'strength': 'Strength',
    'aggression': 'Aggression',
    'jumping': 'Jumping',
    'standing_tackle': 'Standing Tackle',
    'agility': 'Agility',
    'curve': 'Curve',
    'fk_accuracy': 'Free Kick Accuracy',
    'defensive_awareness': 'Def Awareness',
    'sliding_tackle': 'Sliding Tackle',
    'volleys': 'Volleys',
    'positioning': 'Positioning',
    'vision': 'Vision',
    'penalties': 'Penalties',
    'composure': 'Composure',
    'interceptions': 'Interceptions',
    'reactions': 'Reactions',
    'balance': 'Balance',
    'dribbling': 'Dribbling'
}

df_24 = df_24.rename(columns=column_mapping)

In [ ]:
print(f"df_24 tiene {len(df_24.columns)} columnas")
print(f"df_25 tiene: {len(df_25.columns)} columnas")

df_24 tiene 41 columnas
df_25 tiene: 41 columnas

In [ ]:
for col in df_24.columns:
    if col not in df_25.columns:
        print(col)

In [ ]:
dtype = pd.DataFrame({
    'FIFA24': df_24.dtypes,
    'FIFA25': df_25.dtypes
})

dtypes_desiguales = dtype[dtype['FIFA24'] != dtype['FIFA25']]
dtypes_desiguales

                FIFA24   FIFA25
GK Diving        int64  float64
GK Handling      int64  float64
GK Kicking       int64  float64
GK Positioning  object  float64
Height           int64   object
Weak foot       object    int64
Weight           int64   object

In [ ]:
print(df_24['GK Positioning'].unique())
print(df_25['GK Positioning'].unique())

['11' '10' '14' '90' '8' '7' '86' '15' '5' '12' '13' '6' '9' '83' '85'
 '88' '16' '3' '84' '81' '4' '33' '82' '79' '80' '77' '19' '78' '75' '76'
 'Power Header' 'Tiki Taka,Intercept' '2' 'Tiki Taka'
 'Chip Shot,Rapid,Flair' '74' '71' 'Incisive Pass,Technical'
 'Tiki Taka,Technical,Flair,Trivela' 'Finesse Shot,Technical' 'Rapid'
 'Cross Claimer' '18' '72' '73' '69' 'Long Ball Pass,Tiki Taka'
 'Finesse Shot,Long Ball Pass,Tiki Taka,Relentless' '68' 'Long Ball Pass'
 'Technical' nan 'Long Ball Pass,Intercept,Slide Tackle'
 'Finesse Shot,Chip Shot' '70' '67' 'Footwork' 'Technical,Flair' '63' '64'
 '66' '20' 'Finesse Shot' 'Long Ball Pass,Intercept' 'Block' '23' 'Flair'
 'Cross Claimer,Rush Out' 'Long Ball Pass,Rapid'
 'Pinged Pass,Long Ball Pass' 'Chip Shot,Technical'
 'Finesse Shot,Technical,Flair,First Touch' 'Power Shot' '65' '55'
 'Anticipate' '17' '62' '61' 'Technical,Flair,First Touch'
 'Slide Tackle,Long Throw' 'Relentless' '60'
 'Jockey,Block,Slide Tackle,Bruiser' '48' 'Intercept,Slide Tackle' '42'
 'Flair,Trivela' '57' 'Rush Out' '58' '59' 'Power Header,Aerial'
 'Rapid,Flair' 'Finesse Shot,Chip Shot,Technical,Flair,Trivela'
 'Long Throw' '52' '56' '54' '53' '49' '51' 11 15 56 6 51 14 13 10 9 54 8
 7 5 57 12 60 59 53 55 58 49 52 48 16 61 50 46 40 47 44 43 45 41 42]
[nan 87. 90. 88. 86. 84. 85. 83. 82. 79. 80. 81. 78. 76. 77. 75. 73. 72.
 74. 69. 70. 68. 71. 67. 66. 63. 65. 64. 61. 62. 60. 59. 55. 58. 57. 56.
 52. 53. 54. 49. 50. 48. 51. 44. 46. 47. 41. 45. 43. 42.]

In [ ]:
df_24['GK Positioning'] = pd.to_numeric(df_24['GK Positioning'], errors='coerce')

print(f"df_24 en la columna GK Positioning tiene {df_24['GK Positioning'].isna().sum()} valores nulos")
print(f"df_25 en la columna GK Positioning tiene {df_25['GK Positioning'].isna().sum()} valores nulos")

df_24 en la columna GK Positioning tiene 95 valores nulos
df_25 en la columna GK Positioning tiene 14345 valores nulos

In [ ]:
for col in ['GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning']:

    nan_24 = len(df_24[df_24[col].isna()])
    nan_25 = len(df_25[df_25[col].isna()])

    print(f'{col}: 24:{nan_24} vs 25:{nan_25}')

GK Diving: 24:0 vs 25:14345
GK Handling: 24:0 vs 25:14345
GK Kicking: 24:0 vs 25:14345
GK Positioning: 24:95 vs 25:14345

In [ ]:
df_25[-df_25['GK Diving'].isna()]

,Name,OVR,Acceleration,Sprint Speed,Positioning,Finishing,Shot Power,Long Shots,Volleys,Penalties,...,Position,Weak foot,Preferred foot,Height,Weight,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes
8,Gianluigi Donnarumma,89,50,55,14,12,55,18,8,24,...,GK,3,Right,"196cm / 6'5""",90kg / 198lb,90.0,84.0,73.0,87.0,90.0
9,Alisson,89,60,49,13,13,64,14,20,23,...,GK,3,Right,"193cm / 6'4""",91kg / 201lb,86.0,85.0,85.0,90.0,89.0
10,Thibaut Courtois,89,42,52,13,14,57,17,12,27,...,GK,3,Left,"200cm / 6'7""",96kg / 212lb,85.0,89.0,76.0,88.0,90.0
13,Marc-André ter Stegen,89,45,50,11,14,67,10,14,25,...,GK,4,Right,"187cm / 6'2""",85kg / 187lb,86.0,85.0,89.0,86.0,91.0
21,Ederson,88,64,63,20,14,68,18,18,65,...,GK,3,Left,"188cm / 6'2""",86kg / 190lb,87.0,82.0,91.0,86.0,87.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16122,Lim Jun Sub,48,26,18,10,8,39,10,8,10,...,GK,2,Right,"195cm / 6'5""",84kg / 185lb,45.0,51.0,52.0,46.0,52.0
16124,Alex Rando,48,31,22,7,5,38,8,6,17,...,GK,2,Right,"193cm / 6'4""",81kg / 179lb,47.0,47.0,51.0,52.0,46.0
16126,Roh Hee Dong,48,25,26,16,7,40,9,8,15,...,GK,3,Right,"192cm / 6'4""",88kg / 194lb,48.0,50.0,53.0,43.0,50.0
16132,Alexander Turkin,48,22,25,4,8,40,7,6,18,...,GK,3,Right,"180cm / 5'11""",65kg / 143lb,55.0,45.0,53.0,46.0,49.0
16138,Zhou Zhengkai,48,18,30,10,12,37,9,15,13,...,GK,3,Right,"183cm / 6'0""",72kg / 159lb,56.0,49.0,49.0,42.0,46.0

In [ ]:
for col in df_24.columns:

    nan_24 = len(df_24[df_24[col].isna()])
    nan_25 = len(df_25[df_25[col].isna()])

    print(f'{col}: 24:{nan_24} vs 25:{nan_25}')

Name: 24:0 vs 25:0
Height: 24:0 vs 25:0
Weight: 24:0 vs 25:0
Position: 24:0 vs 25:0
OVR: 24:0 vs 25:0
Preferred foot: 24:0 vs 25:0
Weak foot: 24:0 vs 25:0
Crossing: 24:0 vs 25:0
Finishing: 24:0 vs 25:0
Heading Accuracy: 24:0 vs 25:0
Short Passing: 24:0 vs 25:0
Volleys: 24:0 vs 25:0
Dribbling: 24:0 vs 25:0
Curve: 24:0 vs 25:0
Free Kick Accuracy: 24:0 vs 25:0
Long Passing: 24:0 vs 25:0
Ball Control: 24:0 vs 25:0
Acceleration: 24:0 vs 25:0
Sprint Speed: 24:0 vs 25:0
Agility: 24:0 vs 25:0
Reactions: 24:0 vs 25:0
Balance: 24:0 vs 25:0
Shot Power: 24:0 vs 25:0
Jumping: 24:0 vs 25:0
Stamina: 24:0 vs 25:0
Strength: 24:0 vs 25:0
Long Shots: 24:0 vs 25:0
Aggression: 24:0 vs 25:0
Interceptions: 24:0 vs 25:0
Positioning: 24:0 vs 25:0
Vision: 24:0 vs 25:0
Penalties: 24:0 vs 25:0
Composure: 24:0 vs 25:0
Def Awareness: 24:0 vs 25:0
Standing Tackle: 24:0 vs 25:0
Sliding Tackle: 24:0 vs 25:0
GK Diving: 24:0 vs 25:14345
GK Handling: 24:0 vs 25:14345
GK Kicking: 24:0 vs 25:14345
GK Positioning: 24:95 vs 25:14345
GK Reflexes: 24:95 vs 25:14345

In [ ]:
df_24 = df_24.fillna(0)
df_25 = df_25.fillna(0)

In [ ]:
df_24['GK Diving'] = df_24['GK Diving'].astype(np.float64)
df_24['GK Handling'] = df_24['GK Handling'].astype(np.float64)
df_24['GK Kicking'] = df_24['GK Kicking'].astype(np.float64)

In [ ]:
df_25['Height'].unique()

array(['182cm / 6\'0"', '191cm / 6\'3"', '195cm / 6\'5"', '186cm / 6\'1"',
       '176cm / 5\'9"', '181cm / 5\'11"', '188cm / 6\'2"',
       '178cm / 5\'10"', '196cm / 6\'5"', '193cm / 6\'4"',
       '200cm / 6\'7"', '174cm / 5\'9"', '187cm / 6\'2"', '175cm / 5\'9"',
       '171cm / 5\'7"', '169cm / 5\'7"', '185cm / 6\'1"', '173cm / 5\'8"',
       '190cm / 6\'3"', '177cm / 5\'10"', '184cm / 6\'0"',
       '179cm / 5\'10"', '183cm / 6\'0"', '180cm / 5\'11"',
       '172cm / 5\'8"', '192cm / 6\'4"', '168cm / 5\'6"', '199cm / 6\'6"',
       '189cm / 6\'2"', '170cm / 5\'7"', '194cm / 6\'4"', '166cm / 5\'5"',
       '197cm / 6\'6"', '161cm / 5\'3"', '198cm / 6\'6"', '167cm / 5\'6"',
       '165cm / 5\'5"', '163cm / 5\'4"', '202cm / 6\'8"', '164cm / 5\'5"',
       '201cm / 6\'7"', '156cm / 5\'1"', '204cm / 6\'8"', '159cm / 5\'3"',
       '203cm / 6\'8"', '162cm / 5\'4"', '206cm / 6\'9"', '160cm / 5\'3"'],
      dtype=object)

In [ ]:
df_25['Height'] = df_25['Height'].str.extract(r'(\d+)cm').astype(int)
df_25['Height']

0        182
1        191
2        195
3        186
4        176
        ...
16156    169
16157    176
16158    181
16159    187
16160    182
Name: Height, Length: 16161, dtype: int64

In [ ]:
df_25['Weight'].unique()

array(['75kg / 165lb', '82kg / 181lb', '94kg / 207lb', '73kg / 161lb',
       '86kg / 190lb', '68kg / 150lb', '90kg / 198lb', '91kg / 201lb',
       '96kg / 212lb', '72kg / 159lb', '92kg / 203lb', '85kg / 187lb',
       '69kg / 152lb', '67kg / 148lb', '81kg / 179lb', '78kg / 172lb',
       '64kg / 141lb', '87kg / 192lb', '71kg / 157lb', '88kg / 194lb',
       '77kg / 170lb', '65kg / 143lb', '80kg / 176lb', '74kg / 163lb',
       '89kg / 196lb', '66kg / 146lb', '60kg / 132lb', '84kg / 185lb',
       '93kg / 205lb', '79kg / 174lb', '83kg / 183lb', '70kg / 154lb',
       '95kg / 209lb', '76kg / 168lb', '61kg / 134lb', '63kg / 139lb',
       '99kg / 218lb', '59kg / 130lb', '62kg / 137lb', '100kg / 220lb',
       '103kg / 227lb', '98kg / 216lb', '56kg / 123lb', '97kg / 214lb',
       '58kg / 128lb', '55kg / 121lb', '101kg / 223lb', '53kg / 117lb',
       '54kg / 119lb', '57kg / 126lb', '105kg / 231lb', '104kg / 229lb',
       '51kg / 112lb'], dtype=object)

In [ ]:
df_25['Weight'] = df_25['Weight'].str.extract(r'(\d+)kg').astype(int)
df_25['Weight']

0        75
1        82
2        94
3        75
4        73
         ..
16156    62
16157    74
16158    69
16159    71
16160    75
Name: Weight, Length: 16161, dtype: int64

In [ ]:
df_24['Weak foot'].unique()

array(['3 ', '4 ', '5 ', '2 ', '1 ', '4 +1', '5 +1', '2 -1', '3 +1',
       '2 +1', '3 -1', '4 +2', 2, 4, 3, 1, 5], dtype=object)

In [ ]:
def clean_weak_foot(value):
    value = str(value).strip()

    base_value = int(value[0])

    if '+' in value:
        modifier = int(value.split('+')[1].strip())
        return min(base_value + modifier, 5)
    elif '-' in value:
        modifier = int(value.split('-')[1].strip())
        return max(base_value - modifier, 1)
    else:
        return base_value

df_24['Weak foot'] = df_24['Weak foot'].apply(clean_weak_foot)
df_24['Weak foot'].unique()

array([3, 4, 5, 2, 1])

In [ ]:
posiciones = {
    # Arqueros
    'GK': 'Arquero',

    # Defensores
    'CB': 'Defensor', 'LB': 'Defensor', 'RB': 'Defensor',
    'LWB': 'Defensor', 'RWB': 'Defensor',

    # Mediocampistas
    'CDM': 'Mediocampista', 'CM': 'Mediocampista', 'CAM': 'Mediocampista',
    'LM': 'Mediocampista', 'RM': 'Mediocampista',

    # Delanteros
    'LW': 'Delantero', 'RW': 'Delantero', 'CF': 'Delantero', 'ST': 'Delantero'
}

def reductor_categorias(position_str):

    if pd.isna(position_str):
        return ['Unknown']

    positions = [pos.strip() for pos in position_str.split(',')]
    categories = list({posiciones.get(pos, 'Unknown') for pos in positions})

    return categories

df_24['Position'] = df_24['Position'].apply(reductor_categorias)
df_25['Position'] = df_25['Position'].apply(reductor_categorias)

print("\nDistribución de categorías en FIFA 24:")
print(df_24['Position'].explode().value_counts(normalize=True))

print("\nDistribución de categorías en FIFA 25:")
print(df_25['Position'].explode().value_counts(normalize=True))

Distribución de categorías en FIFA 24:
Position
Mediocampista    0.388697
Defensor         0.309243
Delantero        0.209858
Arquero          0.092203
Name: proportion, dtype: float64

Distribución de categorías en FIFA 25:
Position
Mediocampista    0.374049
Defensor         0.335313
Delantero        0.178269
Arquero          0.112369
Name: proportion, dtype: float64

In [ ]:
df_24['Position'].apply(tuple).value_counts()

Position
(Defensor,)                             5020
(Mediocampista,)                        4869
(Delantero,)                            2518
(Arquero,)                              2054
(Delantero, Mediocampista)              2001
(Defensor, Mediocampista)               1713
(Defensor, Delantero)                     80
(Defensor, Delantero, Mediocampista)      76
Name: count, dtype: int64

In [ ]:
df_25['Position'].apply(tuple).value_counts()

Position
(Mediocampista,)    6045
(Defensor,)         5419
(Delantero,)        2881
(Arquero,)          1816
Name: count, dtype: int64

In [ ]:
!pip install fuzzywuzzy
!pip install rapidfuzz

from rapidfuzz import fuzz, process
import re

def normalize_name(name):
    if pd.isna(name):
        return ""
    name = str(name).lower()
    return " ".join(sorted(re.sub(r'[^a-z\s]', '', name).split()))

def preprocess_names(names):
    return np.array([normalize_name(n) for n in names])

def find_common_players(df1, df2, name_col='Name', threshold=85):
    names1 = df1[name_col].dropna().unique()
    names2 = df2[name_col].dropna().unique()

    norm1 = preprocess_names(names1)
    norm2 = preprocess_names(names2)

    name_to_index = {name: idx for idx, name in enumerate(names2)}

    matches = []
    for idx, (orig_name, norm_name) in enumerate(zip(names1, norm1)):
        match = process.extractOne(
            norm_name,
            norm2,
            scorer=fuzz.token_set_ratio,
            score_cutoff=threshold
        )
        if match:
            matched_name = names2[match[2]]
            matches.append((orig_name, matched_name, match[1]))

    return pd.DataFrame(matches, columns=['FIFA24_Name', 'FIFA25_Name', 'Match_Score'])

common_players = find_common_players(df_24, df_25)

print(f"Jugadores en común: {len(common_players)}")
print(common_players.sort_values('Match_Score', ascending=False).head(10))

total_players = len(set(df_24['Name']) | set(df_25['Name']))
coverage = len(common_players) / total_players * 100
print(f"\nCobertura: {coverage:.2f}% de jugadores encontrados en ambos dataframes")

def find_matches(names_24, names_25, threshold=95):
    norm_24 = [normalize_name(n) for n in names_24]
    norm_25 = {normalize_name(n): i for i, n in enumerate(names_25)}

    matches = set()
    for name_24, norm_name in zip(names_24, norm_24):
        best_match = process.extractOne(
            norm_name,
            list(norm_25.keys()),
            scorer=fuzz.token_set_ratio,
            score_cutoff=threshold
        )
        if best_match:
            original_idx = norm_25[best_match[0]]
            matches.add(original_idx)

    return matches

names_24 = df_24['Name'].dropna().unique()
names_25 = df_25['Name'].dropna().unique()
matching_indices = find_matches(names_24, names_25)

df_fifa25_unique = df_25.drop(index=list(matching_indices)).reset_index(drop=True)

print(f"Jugadores originales en FIFA 25: {len(df_25)}")
print(f"Jugadores eliminados (presentes en FIFA 24): {len(matching_indices)}")
print(f"Jugadores únicos en FIFA 25: {len(df_fifa25_unique)}")

Requirement already satisfied: fuzzywuzzy in /usr/local/lib/python3.11/dist-packages (0.18.0)
Requirement already satisfied: rapidfuzz in /usr/local/lib/python3.11/dist-packages (3.13.0)
Jugadores en común: 13442
                  FIFA24_Name       FIFA25_Name  Match_Score
13441   Fredy Chawngthansanga             Fredy        100.0
0        Erling Braut Haaland    Erling Haaland        100.0
13425             Robin Yadav       Robin Yadav        100.0
13424  Derrick Nicholas Silva             Silva        100.0
13423  艾孜买提·凯萨尔 Ezimet Qeyser     Qeyser Ezimet        100.0
13422         刘俊贤 Liu Junxian       Liu Junxian        100.0
13421           Billy Gilmore     Billy Gilmore        100.0
13420        郑钧蔚 Zheng Junwei       Zheng Zheng        100.0
13419       周正凯 Zhou Zhengkai     Zhou Zhengkai        100.0
13418        Tahir Reid-Brown  Tahir Reid-Brown        100.0

Cobertura: 48.77% de jugadores encontrados en ambos dataframes
Jugadores originales en FIFA 25: 16161
Jugadores eliminados (presentes en FIFA 24): 10688
Jugadores únicos en FIFA 25: 5473

In [ ]:
df_25 = df_fifa25_unique.copy()
df_25

,Name,OVR,Acceleration,Sprint Speed,Positioning,Finishing,Shot Power,Long Shots,Volleys,Penalties,...,Position,Weak foot,Preferred foot,Height,Weight,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes
0,Rodri,91,65,66,76,74,92,89,71,62,...,[Mediocampista],4,Right,191,82,0.0,0.0,0.0,0.0,0.0
1,Vini Jr.,90,95,95,87,89,81,83,73,71,...,[Delantero],4,Right,176,73,0.0,0.0,0.0,0.0,0.0
2,Phil Foden,88,89,83,85,88,89,89,59,64,...,[Delantero],3,Left,171,69,0.0,0.0,0.0,0.0,0.0
3,Neymar Jr,87,86,84,81,80,77,75,84,85,...,[Delantero],5,Right,175,68,0.0,0.0,0.0,0.0,0.0
4,Marquinhos,87,76,81,70,59,65,45,35,52,...,[Defensor],3,Right,183,75,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5468,Engson Singh,47,32,31,39,44,48,50,25,43,...,[Mediocampista],3,Right,169,62,0.0,0.0,0.0,0.0,0.0
5469,Ousmane Sylla,47,66,67,47,34,50,33,32,40,...,[Mediocampista],3,Right,176,74,0.0,0.0,0.0,0.0,0.0
5470,Wei Feng,47,55,59,50,47,44,50,32,51,...,[Defensor],3,Right,181,69,0.0,0.0,0.0,0.0,0.0
5471,Won Hui Do,47,69,63,45,24,52,39,33,42,...,[Mediocampista],3,Right,187,71,0.0,0.0,0.0,0.0,0.0
5472,Wu Yuhang,47,51,60,37,31,40,32,26,41,...,[Mediocampista],3,Right,182,75,0.0,0.0,0.0,0.0,0.0

In [ ]:
df_24.info(), df_25.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18331 entries, 0 to 18330
Data columns (total 41 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                18331 non-null  object
 1   Height              18331 non-null  int64
 2   Weight              18331 non-null  int64
 3   Position            18331 non-null  object
 4   OVR                 18331 non-null  int64
 5   Preferred foot      18331 non-null  object
 6   Weak foot           18331 non-null  int64
 7   Crossing            18331 non-null  int64
 8   Finishing           18331 non-null  int64
 9   Heading Accuracy    18331 non-null  int64
 10  Short Passing       18331 non-null  int64
 11  Volleys             18331 non-null  int64
 12  Dribbling           18331 non-null  int64
 13  Curve               18331 non-null  int64
 14  Free Kick Accuracy  18331 non-null  int64
 15  Long Passing        18331 non-null  int64
 16  Ball Control        18331 non-null  int64
 17  Acceleration        18331 non-null  int64
 18  Sprint Speed        18331 non-null  int64
 19  Agility             18331 non-null  int64
 20  Reactions           18331 non-null  int64
 21  Balance             18331 non-null  int64
 22  Shot Power          18331 non-null  int64
 23  Jumping             18331 non-null  int64
 24  Stamina             18331 non-null  int64
 25  Strength            18331 non-null  int64
 26  Long Shots          18331 non-null  int64
 27  Aggression          18331 non-null  int64
 28  Interceptions       18331 non-null  int64
 29  Positioning         18331 non-null  int64
 30  Vision              18331 non-null  int64
 31  Penalties           18331 non-null  int64
 32  Composure           18331 non-null  int64
 33  Def Awareness       18331 non-null  int64
 34  Standing Tackle     18331 non-null  int64
 35  Sliding Tackle      18331 non-null  int64
 36  GK Diving           18331 non-null  float64
 37  GK Handling         18331 non-null  float64
 38  GK Kicking          18331 non-null  float64
 39  GK Positioning      18331 non-null  float64
 40  GK Reflexes         18331 non-null  float64
dtypes: float64(5), int64(33), object(3)
memory usage: 5.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5473 entries, 0 to 5472
Data columns (total 41 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                5473 non-null   object
 1   OVR                 5473 non-null   int64
 2   Acceleration        5473 non-null   int64
 3   Sprint Speed        5473 non-null   int64
 4   Positioning         5473 non-null   int64
 5   Finishing           5473 non-null   int64
 6   Shot Power          5473 non-null   int64
 7   Long Shots          5473 non-null   int64
 8   Volleys             5473 non-null   int64
 9   Penalties           5473 non-null   int64
 10  Vision              5473 non-null   int64
 11  Crossing            5473 non-null   int64
 12  Free Kick Accuracy  5473 non-null   int64
 13  Short Passing       5473 non-null   int64
 14  Long Passing        5473 non-null   int64
 15  Curve               5473 non-null   int64
 16  Dribbling           5473 non-null   int64
 17  Agility             5473 non-null   int64
 18  Balance             5473 non-null   int64
 19  Reactions           5473 non-null   int64
 20  Ball Control        5473 non-null   int64
 21  Composure           5473 non-null   int64
 22  Interceptions       5473 non-null   int64
 23  Heading Accuracy    5473 non-null   int64
 24  Def Awareness       5473 non-null   int64
 25  Standing Tackle     5473 non-null   int64
 26  Sliding Tackle      5473 non-null   int64
 27  Jumping             5473 non-null   int64
 28  Stamina             5473 non-null   int64
 29  Strength            5473 non-null   int64
 30  Aggression          5473 non-null   int64
 31  Position            5473 non-null   object
 32  Weak foot           5473 non-null   int64
 33  Preferred foot      5473 non-null   object
 34  Height              5473 non-null   int64
 35  Weight              5473 non-null   int64
 36  GK Diving           5473 non-null   float64
 37  GK Handling         5473 non-null   float64
 38  GK Kicking          5473 non-null   float64
 39  GK Positioning      5473 non-null   float64
 40  GK Reflexes         5473 non-null   float64
dtypes: float64(5), int64(33), object(3)
memory usage: 1.7+ MB

(None, None)

In [ ]:
for col in df_24.columns:
    col_type_24 = df_24[col].dtype
    col_type_25 = df_25[col].dtype
    if col_type_24 != col_type_25:
        print(f'{col}: {col_type_24} vs {col_type_25}')
        df_25[col] = df_25[col].astype(col_type_24)

In [ ]:
df_24_multi = df_24[df_24['Position'].apply(len) > 1].copy()
df_24_multi

,Name,Height,Weight,Position,OVR,Preferred foot,Weak foot,Crossing,Finishing,Heading Accuracy,...,Penalties,Composure,Def Awareness,Standing Tackle,Sliding Tackle,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes
7,Lionel Andrés Messi Cuccittini,169,67,"[Delantero, Mediocampista]",90,Left,4,83,89,60,...,75,96,20,35,24,6.0,11.0,15.0,14.0,8.0
14,Neymar da Silva Santos Júnior,175,68,"[Delantero, Mediocampista]",89,Right,5,83,83,63,...,85,93,35,32,29,9.0,9.0,15.0,15.0,11.0
17,Federico Santiago Valverde Dipetta,182,78,"[Delantero, Mediocampista]",88,Right,4,78,78,59,...,59,84,79,85,79,6.0,10.0,6.0,15.0,8.0
19,Bernardo Mota Veiga de Carvalho e Silva,173,64,"[Delantero, Mediocampista]",88,Left,3,84,78,54,...,68,89,70,76,60,9.0,10.0,14.0,12.0,9.0
30,Joshua Walter Kimmich,177,75,"[Defensor, Mediocampista]",87,Right,4,91,68,72,...,69,86,81,84,78,8.0,15.0,7.0,15.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18251,Divine Izekor,185,75,"[Delantero, Mediocampista]",49,Right,3,31,45,40,...,50,46,12,11,15,9.0,9.0,12.0,11.0,5.0
18262,Harry O Connor,180,70,"[Delantero, Mediocampista]",49,Right,3,36,38,37,...,44,58,32,32,37,10.0,11.0,14.0,6.0,15.0
18274,Mark Zothanpuia,180,75,"[Defensor, Mediocampista]",49,Left,3,36,36,47,...,42,41,36,41,40,9.0,7.0,9.0,10.0,11.0
18280,Ben Collins,179,71,"[Defensor, Mediocampista]",49,Left,2,49,32,37,...,37,41,43,46,45,15.0,10.0,8.0,5.0,10.0
18318,Cris Nowang Sherpa,167,65,"[Delantero, Mediocampista]",47,Right,3,30,45,37,...,53,49,10,18,15,11.0,14.0,8.0,10.0,11.0

In [ ]:
df_24 = df_24[df_24['Position'].apply(len) == 1].copy()
df_24

,Name,Height,Weight,Position,OVR,Preferred foot,Weak foot,Crossing,Finishing,Heading Accuracy,...,Penalties,Composure,Def Awareness,Standing Tackle,Sliding Tackle,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes
0,Erling Braut Haaland,195,94,[Delantero],91,Left,3,47,96,83,...,86,87,38,47,29,7.0,14.0,13.0,11.0,7.0
1,Kylian Mbappé Lottin,182,75,[Delantero],91,Right,4,78,94,73,...,84,88,26,34,32,13.0,5.0,7.0,11.0,6.0
2,Kevin De Bruyne,181,75,[Mediocampista],91,Right,5,95,85,55,...,83,88,66,70,53,15.0,13.0,5.0,10.0,13.0
3,Rodrigo Hernández Cascante,191,82,[Mediocampista],90,Right,4,71,70,81,...,62,87,92,87,78,10.0,10.0,7.0,14.0,8.0
4,Harry Kane,188,85,[Delantero],90,Right,5,80,95,89,...,92,92,46,46,38,8.0,10.0,11.0,14.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18326,吕佳强 Lü Jiaqiang,180,65,[Defensor],47,Right,3,24,24,43,...,34,37,51,50,53,15.0,12.0,8.0,7.0,15.0
18327,Callum Warren,172,67,[Mediocampista],47,Right,3,37,40,40,...,40,51,29,38,34,7.0,14.0,13.0,7.0,10.0
18328,Ishaan Shishodia,177,70,[Mediocampista],47,Right,3,37,26,40,...,37,44,33,38,42,12.0,11.0,13.0,13.0,13.0
18329,吴宇航 Wu Yuhang,182,75,[Mediocampista],47,Right,3,35,31,42,...,41,39,40,45,51,11.0,12.0,5.0,13.0,8.0
18330,Fredy Chawngthansanga,165,64,[Mediocampista],47,Right,3,46,41,35,...,36,46,31,32,29,12.0,10.0,11.0,6.0,8.0

In [ ]:
df_24.reset_index(drop=True, inplace=True)
df_24

,Name,Height,Weight,Position,OVR,Preferred foot,Weak foot,Crossing,Finishing,Heading Accuracy,...,Penalties,Composure,Def Awareness,Standing Tackle,Sliding Tackle,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes
0,Erling Braut Haaland,195,94,[Delantero],91,Left,3,47,96,83,...,86,87,38,47,29,7.0,14.0,13.0,11.0,7.0
1,Kylian Mbappé Lottin,182,75,[Delantero],91,Right,4,78,94,73,...,84,88,26,34,32,13.0,5.0,7.0,11.0,6.0
2,Kevin De Bruyne,181,75,[Mediocampista],91,Right,5,95,85,55,...,83,88,66,70,53,15.0,13.0,5.0,10.0,13.0
3,Rodrigo Hernández Cascante,191,82,[Mediocampista],90,Right,4,71,70,81,...,62,87,92,87,78,10.0,10.0,7.0,14.0,8.0
4,Harry Kane,188,85,[Delantero],90,Right,5,80,95,89,...,92,92,46,46,38,8.0,10.0,11.0,14.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14456,吕佳强 Lü Jiaqiang,180,65,[Defensor],47,Right,3,24,24,43,...,34,37,51,50,53,15.0,12.0,8.0,7.0,15.0
14457,Callum Warren,172,67,[Mediocampista],47,Right,3,37,40,40,...,40,51,29,38,34,7.0,14.0,13.0,7.0,10.0
14458,Ishaan Shishodia,177,70,[Mediocampista],47,Right,3,37,26,40,...,37,44,33,38,42,12.0,11.0,13.0,13.0,13.0
14459,吴宇航 Wu Yuhang,182,75,[Mediocampista],47,Right,3,35,31,42,...,41,39,40,45,51,11.0,12.0,5.0,13.0,8.0
14460,Fredy Chawngthansanga,165,64,[Mediocampista],47,Right,3,46,41,35,...,36,46,31,32,29,12.0,10.0,11.0,6.0,8.0

In [ ]:
df_24['Position'] = df_24['Position'].apply(
    lambda x: x[0] if isinstance(x, list) and len(x) > 0 else None
).reset_index(drop=True)
df_25['Position'] = df_25['Position'].apply(
    lambda x: x[0] if isinstance(x, list) and len(x) > 0 else None
).reset_index(drop=True)

In [ ]:
columnas_español = {
    'Name': 'Nombre',
    'Height': 'Altura',
    'Weight': 'Peso',
    'Position': 'Posición',
    'OVR': 'Valoración_General',
    'Preferred foot': 'Pie_preferido',
    'Weak foot': 'Pie_débil',
    'Crossing': 'Centros',
    'Finishing': 'Definición',
    'Heading Accuracy': 'Precisión_de_cabeza',
    'Short Passing': 'Pases_cortos',
    'Volleys': 'Voleas',
    'Dribbling': 'Regate',
    'Curve': 'Efecto',
    'Free Kick Accuracy': 'Precisión_en_Tiro_Libre',
    'Long Passing': 'Pases_largos',
    'Ball Control': 'Control_de_balón',
    'Acceleration': 'Aceleración',
    'Sprint Speed': 'Velocidad',
    'Agility': 'Agilidad',
    'Reactions': 'Reacciones',
    'Balance': 'Equilibrio',
    'Shot Power': 'Potencia_de_tiro',
    'Jumping': 'Salto',
    'Stamina': 'Resistencia',
    'Strength': 'Fuerza',
    'Long Shots': 'Tiros_lejanos',
    'Aggression': 'Agresividad',
    'Interceptions': 'Intercepciones',
    'Positioning': 'Posicionamiento',
    'Vision': 'Visión',
    'Penalties': 'Penaltis',
    'Composure': 'Serenidad',
    'Def Awareness': 'Conciencia_defensiva',
    'Standing Tackle': 'Entradas',
    'Sliding Tackle': 'Barridas',
    'GK Diving': 'Portero_Estiradas',
    'GK Handling': 'Portero_Bloqueos',
    'GK Kicking': 'Portero_Saques',
    'GK Positioning': 'Portero_Posicionamiento',
    'GK Reflexes': 'Portero_Reflejos'
}

df_24 = df_24.rename(columns=columnas_español)
df_24_multi = df_24_multi.rename(columns=columnas_español)
df_25 = df_25.rename(columns=columnas_español)

In [ ]:
df_24.to_csv('df_fifa_24.csv', index=False)
df_24_multi.to_csv('df_fifa_24_multi.csv', index=False)
df_25.to_csv('df_fifa_25.csv', index=False)